### PR TITLE
Django 3.0 compatibility

### PR DESCRIPTION
**Pull request by meloncafe**
- delete django six modules
- change urlparse to urlsplit

### CODE REVIEW

**Comment by tony** [comment]
@meloncafe Related: Doing a cleanup PR for travis in #45

**Comment by tony** [comment]
@meloncafe FYI I don't have permission to merge unless tests pass

image

**Comment by tony** [comment]
@meloncafe Can you allow me to edit this PR?

Can you do a rebase on this?

If not, is it okay if I fork this PR / create a new PR based on your commit?

**Comment by tony** [comment]
@meloncafe I created a PR at #47 

I'd like you to get credit for this PR though!  You can cherry-pick `11f271d` into this branch if you want.

You could also see if "Allow edits from maintainers" is checked, I don't think I could edit this PR itself: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

I created a PR to your PR also https://github.com/meloncafe/django-activeurl/pull/1

**Comment by tony** [comment]
@hellysmile Can you override and merge this PR? I can follow up with travis fixes. I just want to make sure @meloncafe gets credit for this :)

**Comment by meloncafe** [comment]
yes, i will checked 'Allow edits from maintainers'
sorry for late

**Comment by tony** [comment]
@meloncafe Thank you

I don't seem to have an option to push. Is it possible you can give me access to push to master on your repo? e.g. https://github.com/meloncafe/django-activeurl

@hellysmile Am I a maintainer on the project? I don't seem to be able to push to this PR, but not sure if the terminology is the same since we're not in an organization

**Comment by meloncafe** [comment]
@tony 
yes, sure
i added 'collaborators' to you
if u accepted, i change permissions
thank you

**Comment by tony** [comment]
@meloncafe On it now :)

**Comment by meloncafe** [comment]
@tony Thank you :D

**Comment by tony** [comment]
@meloncafe Thank you! Merged to master in 88bc5cd !

Looking into getting a package on PyPI ASAP :)

**Comment by tony** [comment]
@meloncafe This is live in `0.2.0`, thank to you. Nice job man!

**Pull request merged**
