### PR TITLE
Object oriented code refactoring

### PR DESCRIPTION
**Pull request by encolpe**
Create a mixin class for rendering abstraction:
- less arguments for methods
- simplier debugging

### CODE REVIEW

**Comment by encolpe** [comment]
Coverage decrease when removing one single line containing a _set_trace_! WTF
And check are failing on all but the code I added. 

- ImportError: cannot import name six
- Fatal RPython error: AssertionError (with core dumped)

CI means nothing if it's not reliable.
All that tests were good with _tox_ in my environment.

**Comment by hellysmile** [comment]
Hey, have You seen this branch https://github.com/hellysmile/django-activeurl/pull/17 ?

**Comment by encolpe** [comment]
I didn't

**Comment by hellysmile** [comment]
Can You refactor Your changes and make pull request to refactor branch? I like Your idea, but I want to keep features from my new branch as well

**Comment by encolpe** [comment]
I will see that on tomorrow. Are you in any irc channel?

**Comment by hellysmile** [comment]
freenode hell_razer

**Comment by tony** [comment]
any update / desire to keep this going @encolpe ?

**Comment by encolpe** [comment]
No, I lost the opportunity to work on it. I'm not working on django anymore.
Sorry

**Pull request closed without merging**
