### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by hellysmile**

### CODE REVIEW

**Comment by tony** [comment]
I think simplifying the CI / support requirements #21 could make the burden on this a bit easier.

**Comment by hellysmile** [comment]
@tony thanks You so much for get package back to life.
Is there any chance that we can get this merged in-to current master? 
This pr saves a lot of readability for switching from a lot of parameters to kwargs (not sure is it good idea or not).

But main thing here - start support jinja templates same way as django after in-depth refactoring of jinja extension

**Comment by hellysmile** [comment]
Maybe it will just easier to copy-paste this jinja tag in-to master?

**Comment by tony** [comment]
Do you want to keep your cache refactor, though? That takes up a big portion of the PR.

**Comment by hellysmile** [comment]
I can not push You to do it, but include version of django-activeurl in-to cache key can be very useful for someone during upgrade, especially when behaviour of packages is changed due awesome `ignore_params` options...

**Comment by tony** [comment]
It'd be good to have push access or to be added to the issue so I can fix the commit w/ you

**Comment by hellysmile** [comment]
Invitation is send, all write access will be granted, except master branch which is becomes protected right now.

**Comment by hellysmile** [comment]
Some missing things

We need setup.py classifier regarding Python3.6

'open' is setup.py must be 'io.open' , 

All if statements must use new bool helper

**Comment by tony** [comment]
Updated

> All if statements must use new bool helper

Can you give me some examples of this by commenting the code?

**Comment by hellysmile** [comment]
This landscape and covverals goes crazy, I think we need to remove them and setup codecov service

**Comment by tony** [comment]
I prefer codecov too. Let's add it to refactor-tests #29

**Comment by hellysmile** [comment]
If statment comment is merge diff missunderstood 

Can You merge refactring tests to this branch and lets see how it goes green together

**Comment by tony** [comment]
I would prefer merging #29 into master first (it looks neater since I like to cite it at https://devel.tech/site/open-source), I'm almost finished with it.

**Pull request merged**
