### PR TITLE
Don't highlight href="#" (matches <=0.1.9 behaviour)

### PR DESCRIPTION
**Pull request by voidus**
Fix for https://github.com/hellysmile/django-activeurl/issues/37

### CODE REVIEW

**Comment by tony** [comment]
Do we want this to be an option? Whether we should treat ``'#`` as active or not?

**Comment by tony** [comment]
I'm OK with the behavior of ``#`` being inactive (as the PR does). Because in practice, the user would be using ``{% url ... #} in their menus, and if they have ``href="#"`` their intention is likely to stub. So fine with me. 👍

**Comment by hellysmile** [comment]
Is there any real usage can when it should be highlighted?

**Comment by tony** [comment]
I can't think of any - other than just wanting stuff to be configurable. I'm fine w/ this behavior (see my rationale in https://github.com/hellysmile/django-activeurl/pull/38#issuecomment-366313377, since we posted the same second :smile:)

**Comment by hellysmile** [comment]
Sounds good! I'll implement deployment to pypi through travis via tags and do a release this weekend

@voidus thanks

**Comment by hellysmile** [comment]
Seems travis has problems right now, it do not runs build, I am dome with pypi on tag, will pubshlish them as soon as travis will be online

**Comment by hellysmile** [comment]
There was my fault with travis, I've done hack for now and deployed 0.1.12 https://pypi.python.org/pypi/django-activeurl/0.1.12

**Pull request merged**
